services:
  - type: web
    name: Hoc Discord Bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python webserver.py
    envVars:
      - key: Token
        sync: true
